//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are your sure to remove record?&apos;);.
        /// </summary>
        internal static string AreYourSureToRemoveRecord {
            get {
                return ResourceManager.GetString("AreYourSureToRemoveRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return confirm(&apos;Are your sure to remove records?&apos;);.
        /// </summary>
        internal static string AreYourSureToRemoveRecords {
            get {
                return ResourceManager.GetString("AreYourSureToRemoveRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System can not init assembly with data model..
        /// </summary>
        internal static string CantInitDataModelAssembly {
            get {
                return ResourceManager.GetString("CantInitDataModelAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugins.
        /// </summary>
        internal static string CustomLinks {
            get {
                return ResourceManager.GetString("CustomLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database name.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database server.
        /// </summary>
        internal static string DatabaseServer {
            get {
                return ResourceManager.GetString("DatabaseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        internal static string DebugMode {
            get {
                return ResourceManager.GetString("DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditPageTitle {
            get {
                return ResourceManager.GetString("EditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File storage connection string.
        /// </summary>
        internal static string FileStorageConnectionString {
            get {
                return ResourceManager.GetString("FileStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File storage url.
        /// </summary>
        internal static string FileStorageUrl {
            get {
                return ResourceManager.GetString("FileStorageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload.
        /// </summary>
        internal static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can upload files to server.
        /// </summary>
        internal static string FileUploadDescription {
            get {
                return ResourceManager.GetString("FileUploadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string FileUploadPageTitle {
            get {
                return ResourceManager.GetString("FileUploadPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create record at.
        /// </summary>
        internal static string InsertPageTitle {
            get {
                return ResourceManager.GetString("InsertPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect login or password.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string LogPageTitle {
            get {
                return ResourceManager.GetString("LogPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage web-application.
        /// </summary>
        internal static string ManagePageDescription {
            get {
                return ResourceManager.GetString("ManagePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string ManagePageTitle {
            get {
                return ResourceManager.GetString("ManagePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model has no tables.
        /// </summary>
        internal static string ModelIsEmpty {
            get {
                return ResourceManager.GetString("ModelIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such item.
        /// </summary>
        internal static string NoSuchItem {
            get {
                return ResourceManager.GetString("NoSuchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records per page.
        /// </summary>
        internal static string RecordPerPage {
            get {
                return ResourceManager.GetString("RecordPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove selected.
        /// </summary>
        internal static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart web-application.
        /// </summary>
        internal static string RestartWebApplication {
            get {
                return ResourceManager.GetString("RestartWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RestartWebApplicationDescription.
        /// </summary>
        internal static string RestartWebApplicationDescription {
            get {
                return ResourceManager.GetString("RestartWebApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServerInformationDescription.
        /// </summary>
        internal static string ServerInformationDescription {
            get {
                return ResourceManager.GetString("ServerInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Information.
        /// </summary>
        internal static string ServerInformationPageTite {
            get {
                return ResourceManager.GetString("ServerInformationPageTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show message.
        /// </summary>
        internal static string ShowMessage {
            get {
                return ResourceManager.GetString("ShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemInformationDescription.
        /// </summary>
        internal static string SystemInformationDescription {
            get {
                return ResourceManager.GetString("SystemInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string SystemInformationPageTite {
            get {
                return ResourceManager.GetString("SystemInformationPageTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System commands.
        /// </summary>
        internal static string SystemLinks {
            get {
                return ResourceManager.GetString("SystemLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemLogDescription.
        /// </summary>
        internal static string SystemLogDescription {
            get {
                return ResourceManager.GetString("SystemLogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System work in &lt;b&gt;Debug&lt;/b&gt; mode..
        /// </summary>
        internal static string SystemWorkInDebugMode {
            get {
                return ResourceManager.GetString("SystemWorkInDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        internal static string TableLinks {
            get {
                return ResourceManager.GetString("TableLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management System.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child records.
        /// </summary>
        internal static string ViewChildRecords {
            get {
                return ResourceManager.GetString("ViewChildRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webapplication address.
        /// </summary>
        internal static string WebApplicationAddress {
            get {
                return ResourceManager.GetString("WebApplicationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to webapplication.
        /// </summary>
        internal static string WebApplicationLink {
            get {
                return ResourceManager.GetString("WebApplicationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webapplication storage connection string.
        /// </summary>
        internal static string WebsiteStorageConnectionString {
            get {
                return ResourceManager.GetString("WebsiteStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Data Management System.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You login as.
        /// </summary>
        internal static string YouLoginAs {
            get {
                return ResourceManager.GetString("YouLoginAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You work with project.
        /// </summary>
        internal static string YouWorkWithProject {
            get {
                return ResourceManager.GetString("YouWorkWithProject", resourceCulture);
            }
        }
    }
}
